### ISSUE TITLE
Port mapping in docker-compose file 

### ISSUE THREAD

**Issue by psychtek** [vubiostat/r-yaml#119]
I am having some trouble with port mappings when generating a yaml file. I create an r object like so: 

```R
YAML <- "
             
version: '3.6'
services:
 rstudio:
  ports:
  - 8787:8787
  image: rocker/rstudio
  container_name: rstudio
  restart: on-failure
  volumes:
  - type: volume
    source: rstudio
    target: /home/rstudio

volumes:
  rstudio:"
```

and then write it to project directory: 

```R

yaml_obj <- yaml::yaml.load(YAML)

yaml::as.yaml(yaml_obj)

yaml::write_yaml(yaml_obj, file = paste0("docker-compose.yml"))

```
The `docker-compose.yml` file
```YAML
version: '3.6'
services:
  rstudio:
    ports: 8787:8787
    image: rocker/rstudio
    container_name: rstudio
    restart: on-failure
    volumes:
    - type: volume
      source: rstudio
      target: /home/rstudio
volumes:
  rstudio: ~
```

When I execute the command: 
```R
system("docker-compose -f docker-compose.yml up -d")
```

I get the following error in the console 
```R
services.rstudio.ports must be a list
```

When I view the docker-compose.yml file the ports arent mapping according to the documentation. Ive had a look over issue #72 and strangely though the docker-compose.yml looks close to being correct when I edit the YAML string object: 

```R
YAML <- "
             
version: '3.6'
services:
 rstudio:
  ports: ['\n', 8787:8787]
  image: test
  container_name: rstudio
  restart: on-failure
  volumes:
  - type: volume
    source: rstudio
    target: /home/rstudio

volumes:
  rstudio:"
```
The updated `docker-compose.yml` file:
```YAML
version: '3.6'
services:
  rstudio:
    ports:
    - ' '
    - 8787:8787
    image: test
    container_name: rstudio
    restart: on-failure
    volumes:
    - type: volume
      source: rstudio
      target: /home/rstudio
volumes:
  rstudio: ~

```
Although this also fails to execute as well.

```R
1 error(s) decoding:

* error decoding 'Ports': Invalid containerPort: 
```
Wrapping the ports in quotes doesnt offer a solution either: 
```YAML
services:
 rstudio:
  ports:
  - '8787:8787'
```

Ive tried other approaches but the ports never seem to map to yaml conventions. Any guidance on where I am going wrong?
