### ISSUE TITLE
feature request: `raw=TRUE` in `write_yaml`

### ISSUE THREAD

**Issue by bschilder** [vubiostat/r-yaml#123]
Hello!, 

Thanks for the awesome package. I'm currently using it to read/write GitHub Actions (GHA) workflow files in my new R package / GH Action called [`rworkflows`](https://github.com/neurogenomics/rworkflows).

I have a scenario where I have a GHA workflow yaml that has the key "on". Thanks to the `handler` arg I managed to read in the yaml file.

However, I couldn't seem to figure out how to prevent the "on" key being written as "'on:'" (in single quotes) when writing back to disk with `write_yaml`. This is an issue for GHA as their parser doesn't recognize keys with quotes.

After some playing around, I figured out that the solution was substituting the quoted character and then using `file(..., raw=TRUE)`, but this feature isn't currently exposed to users via `write_yaml` (as far as I can tell).

## Reprex

```
path <- tempfile(fileext = ".yml")
yml <- yaml::read_yaml("https://raw.githubusercontent.com/neurogenomics/rworkflows/master/inst/yaml/rworkflows_template.yml")
```

### Issue 

```
yaml::write_yaml(yml, path)
```

yaml file looks like:

```yaml
name: rworkflows
'on':
  push:
  - master
  - main
  pull_request:
  - master
  - main
```

### Solution

``` 
result <- gsub(shQuote("on"),"on",yaml::as.yaml(yml))
path <- file(file, "w", encoding = "UTF-8", raw=TRUE)
open(path, "w")
on.exit(close(path))
cat(result, file = path, sep = "")
```

```yaml
name: rworkflows
on:
  push:
  - master
  - main
  pull_request:
  - master
  - main
```

 If it's helpful, I'd be happy to implement the raw arg in `write_yaml` and make a Pull Request. Does that sound ok to you (maintainer[s])?

Thanks!, 
Brian

## Session info

<details>
```

```
</details>
