### ISSUE TITLE
understanding hash table versus data dictionary

### ISSUE THREAD

**Issue by srearl** [vubiostat/r-yaml#132]
Thanks for a tremendously helpful package. Perhaps because I do not work with Python, I am having a difficult time understanding the difference between a hash table and data dictionary specification.

Writing the contents of a simple list to yaml, e.g.:

```
list_of_annotations |> 
  yaml::write_yaml(
    file  = "annotations.yaml",
    column.major = FALSE
  )
```

results in a hash like...

```
05c13ff53c9cbbc19dcdc3acecd30052_10_MicroGM-PER-L:
  name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_10
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
05c13ff53c9cbbc19dcdc3acecd30052_7_MicroS-PER-CentiM:
  name: MicroS-PER-CentiM
  valueLabel: Microsiemens Per Centimeter
  valueURI: http://qudt.org/vocab/unit/MicroS-PER-CentiM
  references: 05c13ff53c9cbbc19dcdc3acecd30052_7
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
05c13ff53c9cbbc19dcdc3acecd30052_8_MicroGM-PER-L:
  name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_8
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
05c13ff53c9cbbc19dcdc3acecd30052_9_MicroGM-PER-L:
  name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_9
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
```

whereas passing the same list through a call to unique():

```
list_of_annotations |> 
  unique() |> 
  yaml::write_yaml(
    file  = "annotations.yaml",
    column.major = FALSE
  )
```

results in a data dictionary specification like...

```
- name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_10
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
- name: MicroS-PER-CentiM
  valueLabel: Microsiemens Per Centimeter
  valueURI: http://qudt.org/vocab/unit/MicroS-PER-CentiM
  references: 05c13ff53c9cbbc19dcdc3acecd30052_7
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
- name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_8
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
- name: MicroGM-PER-L
  valueLabel: Microgram Per Liter
  valueURI: http://qudt.org/vocab/unit/MicroGM-PER-L
  references: 05c13ff53c9cbbc19dcdc3acecd30052_9
  propertyLabel: has unit
  propertyURI: http://qudt.org/schema/qudt/hasUnit
```

I am able to adapt my workflow as needed but I am not following _why_ this is happening, which makes me nervous. Any insight would be appreciated.
