### ISSUE TITLE
Quote all strings?

### ISSUE THREAD

**Issue by noamross** [vubiostat/r-yaml#72]
Is there a way to make all strings be quoted in YAML, not just those containing characters that would result in invalid YAML?

**Comment by viking** [comment]
Do you mean when using `as.yaml`?

**Comment by MarkEdmondson1234** [comment]
I have a similar request as I need to output this yaml:

```yaml
artifacts:
  objects:
    location: "needs to be quoted"
```

but when I use `as.yaml()` I can't default to quoted strings:

```r
yaml::as.yaml(list(artifacts = list(objects = list(location = c("needs to be quoted")))))
```

Is it possible at the moment to force the string quotes?
